### ISSUE TITLE
Missing parameter in dumpCategory

### ISSUE THREAD

**Issue by sleekshop** [sleekshop/jssdk#1]
The depth parameter in the dumpCategory call is missing. This is a feature that we need to implement.

**Comment by torstenlemke** [comment]
Depth param is implemented in package version 2.1.3, see 1a608fdd420012e081ae5c7b162f04d4198cbcd9

It is published to npmjs so you can just go ahead and run `npm update` / `yarn update` or whatever package manager you are using.
